# Generated by Django 2.2.17 on 2020-11-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_book_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookGenre',
            new_name='BookType',
        ),
    ]
