# Generated by Django 2.2.17 on 2020-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20201129_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='early_rates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booktype',
            name='minimum_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
